title: China Podfest 2019
description: "China Podfest 2019. Shanghai, China â€“ September 21, 2019"
url: ""

destination: public
exclude: [public, Rakefile, README.md]

sass:
  style:    :compressed
  sass_dir: assets/stylesheets

# markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages:  ['en', 'cn']
language_default:   'en'
exclude_from_localizations: ["javascript", "images", "css"]
